config/routes.rb
Rails.application.routes.draw do
  # get 'reviews/create'
  devise_for :users
  # root to: 'products#index'
  root to: 'homes#index'

  get '/coffee_quiz', to: 'quizzes#new'
  post '/coffee_quiz', to: 'quizzes#result'

  resources :categories, only: [:index, :show]

  resources :products, only: %i[index show] do
    # resources :reviews, only: [:create]
  end

  resource :cart, only: [:show] do
    post 'add_item', on: :collection
    patch 'update_quantity', on: :collection
    delete 'empty', on: :collection
  end

  resources :checkouts, only: [:new, :create]
  resources :orders, only: [:index, :show]

  resource :wishlist, only: [:show] do
    post 'toggle/:id', to: 'wishlists#toggle_item', as: 'toggle_item'
    member do
      post 'toggle_item'
      delete :remove_item
    end
  end

  get '/confirm_address', to: 'addresses#new'
  post '/confirm_address', to: 'addresses#create'
  get 'calculate_shipping', to: 'addresses#calculate_shipping'


  # Add these new routes for the cart API and cart item updates
  # get '/api/cart', to: 'carts#api_show'
  # patch '/api/cart_items/:id', to: 'cart_items#update'
end

app/models/cart.rb
class Cart < ApplicationRecord
  has_many :cart_items, dependent: :destroy
  has_many :products, through: :cart_items

  def add_product(product)
    current_item = cart_items.find_by(product: product)
    if current_item
      current_item.increment!(:quantity)
    else
      current_item = cart_items.create(product: product, quantity: 1)
    end
    current_item
  end

  def total_price
    cart_items.sum { |item| item.quantity * item.product.price }
  end

  def product_in_cart?(product)
    cart_items.exists?(product: product)
  end

  def total_items
    cart_items.sum(:quantity)
  end
end

app/controllers/carts_controller.rb
class CartsController < ApplicationController
  include CurrentCart
  before_action :set_cart

  def show
    @cart_items = @cart.cart_items.includes(:product)
    render partial: 'cart_contents' if request.xhr?
  end

  def add_item
    product = Product.find(params[:product_id])
    @cart.add_product(product)

    respond_to do |format|
      format.turbo_stream do
        render turbo_stream: [
          turbo_stream.replace("cart_icon_#{product.id}", partial: 'carts/cart_icon', locals: { product: product }),
          turbo_stream.replace("cart_button", partial: 'shared/cart_button', locals: { cart: @cart })
        ]
      end
      format.html { redirect_back(fallback_location: root_path) }
    end
  end

  def update_quantity
    @cart_item = @cart.cart_items.find(params[:item_id])
    new_quantity = @cart_item.quantity + params[:change].to_i

    if new_quantity > 0
      @cart_item.update(quantity: new_quantity)
    else
      @cart_item.destroy
    end

    respond_to do |format|
      format.turbo_stream do
        render turbo_stream: turbo_stream.replace(
          "cart-contents",
          partial: 'carts/cart_contents',
          locals: { cart: @cart }
        )
      end
      format.html { redirect_to cart_path }
    end
  end

  def empty
    @cart.cart_items.destroy_all

    respond_to do |format|
      format.turbo_stream do
        render turbo_stream: [
          turbo_stream.replace("cart-contents", partial: 'carts/cart_contents', locals: { cart: @cart }),
          turbo_stream.replace("cart_button", partial: 'shared/cart_button', locals: { cart: @cart })
        ]
      end
      format.html { redirect_to products_path, notice: 'Cart emptied successfully.' }
    end
  end

  private

  def set_cart
    @cart = Cart.find_by(id: session[:cart_id]) || Cart.create.tap { |cart| session[:cart_id] = cart.id }
  end
end

app/views/carts/_cart_contents.html.erb
<div id="cart-contents" class="text-center p-4">
  <h1 class='afacad-bold text-xl mb-6'>SHOPPING BAG</h1>

  <% if @cart.cart_items.any? %>
    <div class="space-y-4">
      <% @cart.cart_items.each do |cart_item| %>
        <div id="cart_item_<%= cart_item.product.id %>" class="border-b pb-4">
          <p class="font-semibold"><%= cart_item.product.name %></p>

          <p class='afacad'>
            <%= number_to_currency(cart_item.product.price) %> x <%= cart_item.quantity %>
          </p>


          <div class="flex justify-center items-center mt-2">
            <%= button_to '-', update_quantity_cart_path(item_id: cart_item.id, change: -1),
              method: :patch,
              class: 'text-gray-700 py-1 px-3 rounded-l afacad',
              data: { turbo_method: :patch }
            %>

            <span class="bg-slate-100 py-1 px-3 mb-4 afacad"><%= cart_item.quantity %></span>


            <%= button_to '+', update_quantity_cart_path(item_id: cart_item.id, change: 1),
              method: :patch,
              class: 'text-gray-700 py-1 px-3 rounded-r afacad',
              data: { turbo_method: :patch }
            %>
          </div>
        </div>
      <% end %>
      <div class="afacad-bold text-lg mt-6">
        Total: <%= number_to_currency(@cart.total_price) %>
      </div>
   <%= button_to 'Proceed to Checkout', confirm_address_path, method: :get,
  class: 'bg-[#257A57] py-3 px-7 rounded text-white inline-block transition duration-300 afacad hover:shadow-[0_8px_10px_-3px_rgba(0,0,0,0.3)]'
%>
    </div>
  <% else %>
    <p class='afacad mb-4'>Your cart is empty.</p>
    <%= link_to 'Start Shopping', products_path,
      class: 'bg-[#257A57] py-3 px-7 rounded text-white inline-block transition duration-300 afacad hover:shadow-[0_8px_10px_-3px_rgba(0,0,0,0.3)]'
    %>
  <% end %>
</div>

app/views/carts/_cart_icon.html.erb
<%= turbo_frame_tag "cart_icon_#{product.id}" do %>
  <%= button_to add_item_cart_path(product_id: product.id),
                method: :post,
                class: "text-gray-600 hover:text-gray-800",
                form_class: "inline-block",
                data: { turbo_method: :post } do %>
    <i class="fas fa-shopping-cart cart-icon
              <%= @cart && @cart.product_in_cart?(product) ? 'text-black hover:text-gray-700' : 'text-gray-400 hover:text-gray-600' %>
              transition-colors duration-200"
       data-product-id="<%= product.id %>"></i>
  <% end %>
<% end %>

app/views/carts/show.html.erb
<div class="container mx-auto mt-20">
  <%= render 'cart_contents' %>
</div>