config/routes.rb
Rails.application.routes.draw do
  # get 'reviews/create'
  devise_for :users
  # root to: 'products#index'
  root to: 'homes#index'

  get '/coffee_quiz', to: 'quizzes#new'
  post '/coffee_quiz', to: 'quizzes#result'

  resources :categories, only: [:index, :show]

  resources :products, only: %i[index show] do
    # resources :reviews, only: [:create]
  end

  resource :cart, only: [:show] do
    post 'add_item', on: :collection
    patch 'update_quantity', on: :collection
    delete 'empty', on: :collection
  end

  resources :checkouts, only: [:new, :create]
  resources :orders, only: [:index, :show]

  resource :wishlist, only: [:show] do
    post 'toggle/:id', to: 'wishlists#toggle_item', as: 'toggle_item'
    member do
      post 'toggle_item'
      delete :remove_item
    end
  end

  get '/confirm_address', to: 'addresses#new'
  post '/confirm_address', to: 'addresses#create'
  get 'calculate_shipping', to: 'addresses#calculate_shipping'


  # Add these new routes for the cart API and cart item updates
  # get '/api/cart', to: 'carts#api_show'
  # patch '/api/cart_items/:id', to: 'cart_items#update'
end

app/models/wishlist.rb
class Wishlist < ApplicationRecord
  belongs_to :user
  has_many :wishlist_items
  has_many :products, through: :wishlist_items

  def toggle_product(product)
    wishlist_item = wishlist_items.find_by(product: product)

    if wishlist_item
      wishlist_item.destroy
      false
    else
      wishlist_items.create(product: product)
      true
    end
  end

  def remove_product(product)
    wishlist_items.find_by(product: product)&.destroy
  end
end

app/controllers/wishlists_controller.rb
class WishlistsController < ApplicationController
  before_action :authenticate_user!, except: [:toggle_item]
  before_action :set_wishlist, :set_categories, except: [:toggle_item]

  def show
    @wishlist_products = @wishlist.products
  end

  def toggle_item
    @product = Product.find(params[:id])

    if user_signed_in?
      @wishlist = current_user.wishlist || current_user.create_wishlist
      added = @wishlist.toggle_product(@product)
      render_heart_icon(added)
    else
      render_login_prompt
    end
  end

  def remove_item
    @product = Product.find(params[:id])
    @wishlist = current_user.wishlist
    @wishlist.remove_product(@product)

    respond_to do |format|
      format.turbo_stream do
        if @wishlist.products.empty?
          render turbo_stream: [
            turbo_stream.remove("wishlist_item_#{@product.id}"),
            turbo_stream.replace("wishlist_content", partial: 'wishlists/empty_wishlist')
          ]
        else
          render turbo_stream: turbo_stream.remove("wishlist_item_#{@product.id}")
        end
      end
      format.html { redirect_to wishlist_path, notice: 'Product removed from wishlist.' }
    end
  end

  private

  def set_wishlist
    @wishlist = current_user.wishlist || current_user.create_wishlist
  end

  def set_categories
    @categories = Category.all
  end

  def render_heart_icon(added)
    render turbo_stream: turbo_stream.replace(
      "wishlist_icon_#{@product.id}",
      partial: 'wishlists/heart_icon',
      locals: { product: @product, added: added }
    )
  end

  def render_login_prompt
    render turbo_stream: turbo_stream.replace(
      "wishlist_icon_#{@product.id}",
      partial: 'wishlists/login_prompt',
      locals: { product: @product }
    )
  end
end

app/views/wishlists/_empty_wishlist.html.erb
<%= turbo_frame_tag "wishlist_content" do %>
  <div class="flex flex-col items-center justify-center space-y-4 min-h-[50vh]">
    <h1 class="text-center text-black font-thin text-3xl mb-3 afacad">Your wishlist is empty...</h1>
    <%= link_to products_path,
        class: 'text-center bg-[#257A57] py-3 px-7 rounded text-white inline-block transition duration-300 afacad hover:shadow-[0_8px_10px_-3px_rgba(0,0,0,0.3)]',
        data: { turbo: false } do %>
      Start Shopping
    <% end %>
  </div>
<% end %>

app/views/wishlists/_heart_icon.html.erb
<% if user_signed_in? %>
  <%= link_to toggle_item_wishlist_path(product), class: added ? "text-red-500" : "text-gray-400 hover:text-red-500", data: { turbo_method: :post } do %>
    <i class="<%= added ? 'fas' : 'far' %> fa-heart"></i>
  <% end %>
<% else %>
  <%= render 'wishlists/login_prompt', product: product %>
<% end %>

app/views/wishlists/show.html.erb
<div class='container mx-auto mt-28 px-5'>
  <%= turbo_frame_tag "wishlist_content" do %>
    <div class="flex flex-col items-center">
      <% if @wishlist_products.any? %>
        <h1 class="afacad text-3xl text-center mb-8">Your Wishlist</h1>
        <div class="grid grid-cols-1 sm:grid-cols-2 md:grid-cols-3 lg:grid-cols-4 xl:grid-cols-5 gap-4 justify-items-center">
          <% @wishlist_products.each do |product| %>
            <%= turbo_frame_tag "wishlist_item_#{product.id}" do %>
              <div class="bg-white rounded-lg shadow-md hover:shadow-lg transition-shadow duration-200 overflow-hidden relative w-full max-w-xs">
                <%= link_to product_path(product), class: "block" do %>
                  <img src="<%= product.image %>" alt="<%= product.name %>" class="w-full h-48 object-cover">
                  <div class="p-4">
                    <h2 class="text-sm font-semibold text-black afacad"><%= product.name %></h2>
                    <div class="flex items-center justify-between mt-1">
                      <p class="text-xs font-bold text-black">
                        <%= number_to_currency(product.price, unit: "$", format: "%u%n") %>
                      </p>
                    </div>
                  </div>
                <% end %>
                <div class="absolute -bottom-2 right-4 flex space-x-2">
                  <%= button_to remove_item_wishlist_path(id: product.id), method: :delete, class: "text-red-500 hover:text-red-700" do %>
                    <i class="fas fa-trash"></i>
                  <% end %>
                  <%= turbo_frame_tag "cart_icon_#{product.id}" do %>
                    <%= render 'carts/cart_icon', product: product %>
                  <% end %>
                </div>
              </div>
            <% end %>
          <% end %>
        </div>
      <% else %>
        <%= render 'empty_wishlist' %>
      <% end %>
    </div>
  <% end %>
  <% if @wishlist_products.respond_to?(:total_pages) %>
    <div class="mt-4 flex justify-center">
      <%= paginate @wishlist_products %>
    </div>
  <% end %>
</div>